/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MailManagerPanel.java
 *
 * Created on 22-Apr-2010, 11:36:14
 */

package org.jecars.client.gui;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import javax.jcr.observation.Event;
import org.jecars.client.JC_Clientable;
import org.jecars.client.JC_Exception;
import org.jecars.client.JC_Filter;
import org.jecars.client.JC_Nodeable;
import org.jecars.client.nt.JC_MailManagerNode;
import org.jecars.client.nt.JC_ToolNode;

/**
 *
 * @author weert
 */
public class MailManagerPanel extends javax.swing.JPanel {

    private GUI_Frame          mGUIFrame    = null;
    private JC_MailManagerNode mMailManager = null;
    private transient List<JC_Nodeable> mMailLinks = new ArrayList<JC_Nodeable>();

    /** Creates new form MailManagerPanel */
    public MailManagerPanel() {
      initComponents();
      return;
    }

    /** setClient
     *
     * @param pClient
     * @throws JC_Exception
     */
    public void setClient( final GUI_Frame pFrame, final JC_Clientable pClient ) throws JC_Exception {
      mGUIFrame    = pFrame;
      mMailManager = (JC_MailManagerNode)pClient.getNode( "/JeCARS/ApplicationSources/AdminApp/Tools/new/MailManager" ).morphToNodeType();
      refresh();
      return;
    }

    /** refresh
     *
     * @throws JC_Exception
     */
    public void refresh() throws JC_Exception {
      if (mMailManager!=null) {
        final JC_Nodeable dms = mMailManager.getNode( "DefaultMailServer" );
        if (dms.hasProperty( "jecars:SMTPHost" )) {
          mDefaultSMTPHost.setText( dms.getProperty( "jecars:SMTPHost" ).getValueString() );
        }
        mObsPath1.setText( "" );
        mObsPath2.setText( "" );
        mObsPath3.setText( "" );
        mObsPath4.setText( "" );
        mObsPath5.setText( "" );
        mUser1.setText( "" );
        mUser2.setText( "" );
        mUser3.setText( "" );
        mUser4.setText( "" );
        mUser5.setText( "" );
        mRemove1.setEnabled( false );
        mRemove2.setEnabled( false );
        mRemove3.setEnabled( false );
        mRemove4.setEnabled( false );
        mRemove5.setEnabled( false );
        mMailLinks.clear();
        final JC_Filter filter = JC_Filter.createFilter();
        filter.addCategory( "jecars:MailLink" );
        final Collection<JC_Nodeable> mailLinks = mMailManager.getNode( "MailLinks" ).getNodes( null, filter, null );
        final Iterator<JC_Nodeable>   it = mailLinks.iterator();
        JC_Nodeable ml;
        if (it.hasNext()) {
          ml = it.next();
          mMailLinks.add( ml );
          mObsPath1.setText( ml.getProperty( "jecars:ObservationPath" ).getValueString() );
          mUser1.setText( ml.getProperty( "jecars:User" ).getValueString() );
          mRemove1.setEnabled( true );
          if (it.hasNext()) {
            ml = it.next();
            mMailLinks.add( ml );
            mObsPath2.setText( ml.getProperty( "jecars:ObservationPath" ).getValueString() );
            mUser2.setText( ml.getProperty( "jecars:User" ).getValueString() );
            mRemove2.setEnabled( true );
            if (it.hasNext()) {
              ml = it.next();
              mMailLinks.add( ml );
              mObsPath3.setText( ml.getProperty( "jecars:ObservationPath" ).getValueString() );
              mUser3.setText( ml.getProperty( "jecars:User" ).getValueString() );
              mRemove3.setEnabled( true );
              if (it.hasNext()) {
                ml = it.next();
                mMailLinks.add( ml );
                mObsPath4.setText( ml.getProperty( "jecars:ObservationPath" ).getValueString() );
                mUser4.setText( ml.getProperty( "jecars:User" ).getValueString() );
                mRemove4.setEnabled( true );
                if (it.hasNext()) {
                  ml = it.next();
                  mMailLinks.add( ml );
                  mObsPath5.setText( ml.getProperty( "jecars:ObservationPath" ).getValueString() );
                  mUser5.setText( ml.getProperty( "jecars:User" ).getValueString() );
                  mRemove5.setEnabled( true );
                }
              }
            }
          }
        }
      }
      return;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mDefaultSMTPHost = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mObsPath1 = new javax.swing.JTextField();
        mUser1 = new javax.swing.JTextField();
        mRemove1 = new javax.swing.JButton();
        mObsPath2 = new javax.swing.JTextField();
        mUser2 = new javax.swing.JTextField();
        mRemove2 = new javax.swing.JButton();
        mObsPath3 = new javax.swing.JTextField();
        mUser3 = new javax.swing.JTextField();
        mRemove3 = new javax.swing.JButton();
        mObsPath4 = new javax.swing.JTextField();
        mUser4 = new javax.swing.JTextField();
        mRemove4 = new javax.swing.JButton();
        mObsPath5 = new javax.swing.JTextField();
        mUser5 = new javax.swing.JTextField();
        mRemove5 = new javax.swing.JButton();
        mObsPathAdd = new javax.swing.JTextField();
        mUserAdd = new javax.swing.JTextField();
        mAdd = new javax.swing.JButton();

        mOk.setText("Close");
        mOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mOkActionPerformed(evt);
            }
        });

        jLabel1.setText("Default SMTP Host");

        mDefaultSMTPHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mDefaultSMTPHostActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mail links", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        jLabel2.setText("Observation Path");

        jLabel3.setText("User");

        mObsPath1.setEditable(false);

        mUser1.setEditable(false);

        mRemove1.setText("Remove");
        mRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRemove1ActionPerformed(evt);
            }
        });

        mObsPath2.setEditable(false);

        mUser2.setEditable(false);

        mRemove2.setText("Remove");
        mRemove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRemove2ActionPerformed(evt);
            }
        });

        mObsPath3.setEditable(false);

        mUser3.setEditable(false);

        mRemove3.setText("Remove");
        mRemove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRemove3ActionPerformed(evt);
            }
        });

        mObsPath4.setEditable(false);

        mUser4.setEditable(false);

        mRemove4.setText("Remove");
        mRemove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRemove4ActionPerformed(evt);
            }
        });

        mObsPath5.setEditable(false);

        mUser5.setEditable(false);

        mRemove5.setText("Remove");
        mRemove5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRemove5ActionPerformed(evt);
            }
        });

        mObsPathAdd.setText("/JeCARS/default/Events/");

        mUserAdd.setText("/JeCARS/default/Users/{username}");

        mAdd.setText("Add");
        mAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mObsPath2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(mObsPath1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(mUser2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mRemove2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mRemove1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mObsPath3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mUser3, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mRemove3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mObsPathAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(mObsPath5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                            .addComponent(mObsPath4, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(mUser4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mRemove4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mUserAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(mUser5, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mRemove5, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mObsPath1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mRemove1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRemove2)
                    .addComponent(mObsPath2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRemove3)
                    .addComponent(mObsPath3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRemove4)
                    .addComponent(mObsPath4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mRemove5)
                    .addComponent(mUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mObsPath5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mObsPathAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mUserAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mAdd)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mDefaultSMTPHost, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mDefaultSMTPHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mOk)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAddActionPerformed
      try {
        final JC_Nodeable mls = mMailManager.getNode( "MailLinks" );
        final JC_Nodeable ml = mls.addNode( "MailLink_" + System.currentTimeMillis(), "jecars:MailLink" );
        ml.setProperty( "jecars:NodeType", "jecars:Event" );
        ml.setProperty( "jecars:EventType", Event.NODE_ADDED );
        ml.setProperty( "jecars:ObservationPath", mObsPathAdd.getText() );
        ml.setProperty( "jecars:User", mUserAdd.getText() );
        ml.save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      }
      return;
    }//GEN-LAST:event_mAddActionPerformed

    private void mOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mOkActionPerformed
      mGUIFrame.setVisible( false );
      return;
    }//GEN-LAST:event_mOkActionPerformed

    private void mRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRemove1ActionPerformed
      try {
        mMailLinks.get(0).removeNode();
        mMailLinks.get(0).save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      } finally {
      }
      return;
    }//GEN-LAST:event_mRemove1ActionPerformed

    private void mRemove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRemove2ActionPerformed
      try {
        mMailLinks.get(1).removeNode();
        mMailLinks.get(1).save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      } finally {
      }
      return;
    }//GEN-LAST:event_mRemove2ActionPerformed

    private void mRemove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRemove3ActionPerformed
      try {
        mMailLinks.get(2).removeNode();
        mMailLinks.get(2).save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      } finally {
      }
      return;
    }//GEN-LAST:event_mRemove3ActionPerformed

    private void mRemove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRemove4ActionPerformed
      try {
        mMailLinks.get(3).removeNode();
        mMailLinks.get(3).save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      } finally {
      }
      return;
    }//GEN-LAST:event_mRemove4ActionPerformed

    private void mRemove5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRemove5ActionPerformed
      try {
        mMailLinks.get(4).removeNode();
        mMailLinks.get(4).save();
        refresh();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      } finally {
      }
      return;
    }//GEN-LAST:event_mRemove5ActionPerformed

    private void mDefaultSMTPHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mDefaultSMTPHostActionPerformed
      try {
        mMailManager.setSMTPHost( mDefaultSMTPHost.getText() );
        mMailManager.save();
      } catch( JC_Exception je ) {
        mGUIFrame.reportException( je );
      }
      return;
    }//GEN-LAST:event_mDefaultSMTPHostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mAdd;
    private javax.swing.JTextField mDefaultSMTPHost;
    private javax.swing.JTextField mObsPath1;
    private javax.swing.JTextField mObsPath2;
    private javax.swing.JTextField mObsPath3;
    private javax.swing.JTextField mObsPath4;
    private javax.swing.JTextField mObsPath5;
    private javax.swing.JTextField mObsPathAdd;
    private javax.swing.JButton mOk;
    private javax.swing.JButton mRemove1;
    private javax.swing.JButton mRemove2;
    private javax.swing.JButton mRemove3;
    private javax.swing.JButton mRemove4;
    private javax.swing.JButton mRemove5;
    private javax.swing.JTextField mUser1;
    private javax.swing.JTextField mUser2;
    private javax.swing.JTextField mUser3;
    private javax.swing.JTextField mUser4;
    private javax.swing.JTextField mUser5;
    private javax.swing.JTextField mUserAdd;
    // End of variables declaration//GEN-END:variables

}
