/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MailManagerFrame.java
 *
 * Created on 22-Apr-2010, 11:36:25
 */

package org.jecars.client.gui;

import javax.swing.UIManager;
import org.jecars.client.JC_Clientable;
import org.jecars.client.JC_Exception;
import org.jecars.client.JC_Nodeable;
import org.jecars.client.nt.JC_ToolNode;

/**
 *
 * @author weert
 */
public class MailManagerFrame extends GUI_Frame {


    /** Creates new form MailManagerFrame
     */
    public MailManagerFrame() {
      initComponents();
      return;
    }

    /** setClient
     *
     * @param pClient
     */
    @Override
    public void setClient( final JC_Clientable pClient ) throws JC_Exception {
      super.setClient( pClient );
      mailManagerPanel1.setClient( this, pClient );
      return;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailManagerPanel1 = new org.jecars.client.gui.MailManagerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mailManagerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mailManagerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
      try {
        UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
      } catch( Exception e ) {
        e.printStackTrace();
      }
      MailManagerFrame.start( new MailManagerFrame(), args);
      return;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jecars.client.gui.MailManagerPanel mailManagerPanel1;
    // End of variables declaration//GEN-END:variables

}
