/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersManagerFrame.java
 *
 * Created on 24-jun-2009, 21:30:28
 */

package org.jecars.client.gui;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jecars.client.JC_Clientable;
import org.jecars.client.JC_Factory;
import org.jecars.client.scripts.JCS_defaultScript;
import org.jecars.client.scripts.JCS_scriptClient;

/**
 *
 * @author weert
 */
public class UsersManagerFrame extends javax.swing.JFrame {

    /** Creates new form UsersManagerFrame */
    public UsersManagerFrame() {
      initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagerPanel1 = new org.jecars.client.gui.UserManagerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserManager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userManagerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main( String args[] ) {
        try {
          UIManager.setLookAndFeel( UIManager.getSystemLookAndFeelClassName() );
        } catch( Exception e ) {
          e.printStackTrace();
        }

        final JCS_defaultScript ds = new JCS_defaultScript();
        ds.parseArguments( args );
        if (ds.mShowLogin || ("".equals( ds.mUsername)) || ("".equals( ds.mPassword )) || ("".equals( ds.mJeCARSServer ))) {
          final LoginDialog ld = new LoginDialog( null, true );
          if (!"".equals( ds.mUsername )) {
            ld.setUserName( ds.mUsername );
          }
          if (!"".equals( ds.mPassword )) {
            ld.setPassword( ds.mPassword.toCharArray() );
          }
          if (!"".equals( ds.mJeCARSServer )) {
            ld.setServer( ds.mJeCARSServer );
          }
          ld.setVisible( true );
          if (ld.isOk()) {
            ds.mUsername      = ld.getUserName();
            ds.mPassword      = new String( ld.getPassword() );
            ds.mJeCARSServer  = ld.getServer();
          } else {
            System.exit( 0 );
          }
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              try {
                final UsersManagerFrame umf = new UsersManagerFrame();
                final JC_Clientable client = JC_Factory.createClient( ds.mJeCARSServer );
                client.setCredentials( ds.mUsername, ds.mPassword.toCharArray() );
                umf.userManagerPanel1.setClient( client );
                umf.setVisible(true);
              } catch( Exception e ) {
                e.printStackTrace();
                JOptionPane.showMessageDialog( null, "<html>" + e.getMessage() + "</html>", "Error", JOptionPane.ERROR_MESSAGE );
              }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected org.jecars.client.gui.UserManagerPanel userManagerPanel1;
    // End of variables declaration//GEN-END:variables

}
