/*
 * Copyright 2007-2008 NLR - National Aerospace Laboratory
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jecars.tools;

/** CARS_ToolInstanceListener
 *
 * @version $Id: CARS_ToolInstanceListener.java,v 1.1 2007/12/21 15:06:32 weertj Exp $
 */
public interface CARS_ToolInstanceListener {

  
  /** Listen to instance state changes
   * @param pEvent holds the event which caused the call
   */
  public void stateChanged( final CARS_ToolInstanceEvent pEvent );

  /** Listen to tool instance exceptions, tool instance exceptions are exception which
   * are generated by external tools.
   * @param pEvent holds the event which caused the call
   */
  public void toolInstanceException( final CARS_ToolInstanceEvent pEvent );

  /** Listen to instance exceptions
   * @param pEvent holds the event which caused the call
   */
  public void generalException( final CARS_ToolInstanceEvent pEvent );

  /** Listen to instance reports
   * @param pEvent holds the event which caused the call
   */
  public void reports( final CARS_ToolInstanceEvent pEvent );

  /** Listen to message reports
   * @param pEvent holds the event which caused the call
   */
  public void reportMessage( final CARS_ToolInstanceEvent pEvent );
    
}
